name: CI
run-name: CI — ${{ github.head_ref || github.ref_name }}

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  quality:
    uses: infinitetoken/Workflows/.github/workflows/npm-ci.yml@v0.1.3
